/*
 * Rodolfo Zacarias - 2025.
 *
 * All rights reserved. This software is the exclusive property of Rodolfo Zacarias.
 * Redistribution, modification, or use of this code is permitted only under the terms
 * of the GNU General Public License (GPL) as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */
package com.rodolfoz.textaiapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user data model stored in the database.
 *
 * @property id The unique identifier for the user. Auto-generated by the database.
 * @property name The name of the user.
 * @property age The age of the user.
 * @property gender The gender of the user.
 * @property phone The phone number of the user.
 * @property email The email address of the user.
 * @property city The city where the user resides.
 * @property state The state where the user resides.
 * @property country The country where the user resides.
 */
@Entity(tableName = "user_data")
class UserDataModel(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    var name: String = "",
    var age: Int = 0,
    var gender: String = "",
    var phone: String = "",
    var email: String = "",
    var city: String = "",
    var state: String = "",
    var country: String = "",
)
