/*
 * Rodolfo Zacarias 2025
 *
 * All rights reserved. This software is the property of Rodolfo Zacarias.
 * Reproduction, distribution, or modification without written permission is prohibited.
 *
 * Use is subject to a license agreement. The author is not liable for any
 * direct or indirect damages resulting from use of this software.
 */
package com.rodolfoz.textaiapp.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user data model stored in the database.
 *
 * @property id The unique identifier for the user. Auto-generated by the database.
 * @property name The name of the user.
 * @property age The age of the user.
 * @property gender The gender of the user.
 * @property phone The phone number of the user.
 * @property email The email address of the user.
 * @property city The city where the user resides.
 * @property state The state where the user resides.
 * @property country The country where the user resides.
 * @property login The login/username for authentication.
 * @property password The hashed password for authentication.
 */
@Entity(tableName = "user_data")
class UserDataModel(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    var name: String = "",
    var age: Int = 0,
    var gender: String = "",
    var phone: String = "",
    var email: String = "",
    var city: String = "",
    var state: String = "",
    var country: String = "",
    var login: String = "",
    var password: String = "",
    // Firebase UID (populate after successful Firebase Auth). New column, default empty.
    var firebaseUid: String = ""
)
